name: Bantai Deploy Dewaweb

on:
  push:
    branches:
      - main # Pastikan ini sesuai dengan branch utama lu

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build
        run: |
          npm install
          npm run build
        env:
          NEXT_PUBLIC_GEMINI_API_KEY: ${{ secrets.NEXT_PUBLIC_GEMINI_API_KEY }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: 🚀 Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Kita upload ke folder 'apps' agar tidak bentrok dengan sistem cPanel
          local-dir: ./
          server-dir: apps/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/src/**
            README.md
            .env*
            .gitignore
            package-lock.json